### ISSUE TITLE
high cpu usage 2

### ISSUE THREAD

**Issue by idnovic** [X3n0m0rph59/precached#14]
I found that precached uses 9-20% cpu atm.
The cpu usage was not as high before.

What command can I run to find out what precached is calculating?
I stopped the process atm but I want to investigate it.

**Comment by idnovic** [comment]
Better idea: Above question still stands but also how to I reset precached completely?
Maybe something got in the way since I run the dev version since a few days now.

**Comment by X3n0m0rph59** [comment]
> I found that precached uses 9-20% cpu atm.
The cpu usage was not as high before.

Maybe it is optimizing trace logs in the background? Can you reproduce this with log_level set to debug and show some logs?

> What command can I run to find out what precached is calculating?

You can use `perf top` to investigate what functions are the main culprit. Since you are running the release build of precached (without debug symbols) you may find `perf trace` better suited. It will show you what system calls are executed by precached.

```bash
$ sudo perf top -p $(pgrep precached)
$ sudo perf trace -p $(pgrep precached)
```
> how to I reset precached completely?

To completely reset the state of precached you may run these commands:

```bash
$ sudo systemctl stop precached
$ sudo iotracectl clear 
$ sudo precachedctl plugins hot-applications optimize
```

**Comment by idnovic** [comment]
![Bildschirmfoto vom 2019-07-07 16-27-24](https://user-images.githubusercontent.com/28260793/60769867-3ccc2200-a0d5-11e9-81d7-72a1cb41532e.png)
[log.txt.zip](https://github.com/X3n0m0rph59/precached/files/3365742/log.txt.zip)

the screenshot is the first command and the log is just 10 seconds of the second command

**Comment by X3n0m0rph59** [comment]
Thank you for investigating this! The screenshot looks interesting indeed!
Looks like an issue in a dependency of precached (`sys_info` crate). Let's see whether I can reproduce this...

**Comment by idnovic** [comment]
I deleted now the state of precached as you guided above. Still need to do a restart

**Comment by idnovic** [comment]
So it seems that you need to revert the systemd private tmp settings.
After I cleared precached and restarted no preloading was done. I reverted the config and now the preloading works.

I do not understand. Why precached can not access its own tmp dir?

**Comment by idnovic** [comment]
It seems that it was able to access the old files maybe even write to them but without existing files it did not work.

**Comment by X3n0m0rph59** [comment]
> So it seems that you need to revert the systemd private tmp settings.
After I cleared precached and restarted no preloading was done. I reverted the config and now the preloading works.

OK, I reverted the change!

> I do not understand. Why precached can not access its own tmp dir?

I will investigate this, trying to re-enable all systemd protection features that are applicable.

**Comment by idnovic** [comment]
I did not had this high cpu usage again. Well at least not yet. 

Between the options below

fixed by clearing tracelogs, fixed by deactivating private tmp, fixed by blacklisting /app/**/*,

But I will watch out for it.

**Comment by idnovic** [comment]
![Bildschirmfoto vom 2019-07-09 13-58-51](https://user-images.githubusercontent.com/28260793/60886413-7752cd80-a241-11e9-9056-09f33ddf05b4.png)
[log.txt.zip](https://github.com/X3n0m0rph59/precached/files/3372824/log.txt.zip)

Happend again. Newest precached version and I set it to use the precached user.

I can tell now that it has nothing to do with /app/**/*

**Comment by idnovic** [comment]
I forgot that precached runs as its own user now. I need to use sudo with precachedtop. I removed the last sentence of the above comment about precachedtop not working.

**Comment by idnovic** [comment]
Something new happened. Precached uses now 25% CPU directly after power up.
Yesterday I stopped the precached service because of the high CPU use. Today precached seems to hick up at the same point. 

Does this mean a single trace log is responsible?

![Bildschirmfoto vom 2019-07-10 10-59-18](https://user-images.githubusercontent.com/28260793/60956230-e25bdd00-a2f1-11e9-82de-be28d867a75c.png)
[log.txt.zip](https://github.com/X3n0m0rph59/precached/files/3376662/log.txt.zip)

**Comment by idnovic** [comment]
![Bildschirmfoto vom 2019-07-10 21-57-26](https://user-images.githubusercontent.com/28260793/61001015-38f70480-a34e-11e9-9e3e-ab70c839f0c2.png)

This looks like repeat and repeat. I currently can not use precached at all. CPU usage is after start up at 25% and not going anywhere.

_I will reset it again later._  Edit: After I created log files.

> reproduce this with log_level set to debug

How can I set the log level to debug?

**Comment by X3n0m0rph59** [comment]
Sorry, for the inconvenience, I will prepare a new copr build of precached today!

To set the log level to `debug` or `trace`, please edit the file `log4rs.yaml`

```bash
sudoedit /etc/precached/log4rs.yaml
```

Please find line 30, and change it to:

`level: debug` or `level: trace` for even more log output.

**Comment by X3n0m0rph59** [comment]
I just pushed `precached-1.7.1-0`, the Copr build should be finished soon!

Please note that this build ships with a pretty invasive change to the memory accounting. To fully support ZRAM, swap is now included into the calculations (added to the installed RAM size).
As a consequence, one needs to re-tune the parameters set in `precached.conf`. On my development laptop with 4GiB (3.71 GiB usable) of RAM and 4.72 GiB of swap space (ZRAM and swap partition) I am now using these values:

```bash
# Memory management settings
available_mem_critical_threshold=45
available_mem_upper_threshold=40
available_mem_lower_threshold=25
```

Precached now performs the following calculations:

```rust
total_memory = ram_size + swap_size
mem_used = (ram_size - ram_used) + swap_used
percentage = mem_used * 100 / total_memory
```

So if you have 4 GiB of RAM and approx. 4GiB of swap you just need to halve your `available_mem_*` percentage settings, to account for the changes in `precached-1.7.1`.

**Comment by idnovic** [comment]
_I want to try the log file thing in the next hour. Where do I find the log file after I set the setting to debug?_

Edit, found it.
 ```
 # logfile:
  #   kind: file
  #   path: "/var/log/precached.log"
  #   encoder:
  #     pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} [{l}]: {M}:{L} - {m}{n}"
```

**Comment by X3n0m0rph59** [comment]
You will find it in the systemd journal. You may use this command to dump it to a file:

`$ sudo journalctl -b -u precached > precached-debug-$(date --iso).log`

**Comment by idnovic** [comment]
I will use journald. Good point. Thank you.

**Comment by idnovic** [comment]
Only works with precached.service instead of just precached for me but you will have your log in a moment. 26mb.

**Comment by idnovic** [comment]
[precached-debug-log-2019-07-11.log.zip](https://github.com/X3n0m0rph59/precached/files/3382069/precached-debug-log-2019-07-11.log.zip)

I will reset precached now and update it to the newest version including necessary config changes.

**Comment by idnovic** [comment]
I do not know if this is related but I have the following set
```
vm.swappiness=85
vm.vfs_cache_pressure=75
vm.dirty_background_ratio = 3
vm.dirty_ratio = 7
vm.overcommit_memory = 2
vm.overcommit_ratio=75
vm.dirty_background_bytes=16777216
vm.dirty_bytes=16777216
```

I wanted to start gnome-twitch (twitch.tv player) during my current test and I was not able to. Error was:
`FATAL: Could not allocate gigacage memory with maxAlignment = 34359738368, totalSize = 103079215104.`
Workaround `GIGACAGE_ENABLED=no` environment variable.

It is possible that precached faced the same error.
The responsible sysctl settings are:
```
vm.overcommit_ratio = 
vm.overcommit_memory = 
```

I found a bug report for atril, the document viewer of mate desktop. Same error but it happened because atril wanted to mmap 128GB of memory (the system had 16GB).

The above settings for sysctl are a trial for my memory limited laptop. I think you have a better understanding if precached needs memory overcommit and if my above settings are interfering.

**Comment by X3n0m0rph59** [comment]
Regarding your virtual memory subsystem configuration:
 
```
vm.swappiness=85
vm.vfs_cache_pressure=75
vm.dirty_background_ratio = 3
vm.dirty_ratio = 7
vm.overcommit_memory = 2
vm.overcommit_ratio=75
vm.dirty_background_bytes=16777216
vm.dirty_bytes=16777216
```

This looks reasonable except for:

```
vm.overcommit_memory = 2   # <- will lead to application crashes
```

I don't think that this will work out as intended! You are risking lots of software to fail. Overcommit is basically required by every process that calls `fork()`. If the process has a reasonably large vmsz (size of virtual memory allocated address space), it will crash without Linux being able to overcommit memory. Additionally, most memory allocators have a large amount of overhead, in that they consume huge amounts of address space (not memory though). The Java VM may serve as an example here.

Precached therefore needs overcommit memory enabled too. The precached process' vm size, directly after re-booting is currently larger than my installed RAM size.

**Comment by idnovic** [comment]
Okay I will change this to
`vm.overcommit_memory = 0`

An explanation for the bug could be that precached did not unload precached files for me before 1.7.1 and grew bigger and bigger(like java). And at a certain point it was not able to allocate enough memory. But I can not see a related output of this. Precached did not seem to know what wrong is.

Precached allocated up to 1.7GB ram before. Never over 2GB. So it did work with more than 1GB.

Maybe add a memory information profiler for precached. This could help with error reports. Just collect important information at startup and put it inside the log file of precached.

**Comment by idnovic** [comment]
```
CommitLimit = (total_RAM - total_huge_TLB) *
                         overcommit_ratio / 100 + total_swap
```

So this is how linux calculates the over commit in mode 2.
I will try to increase this first before I try to change it back to 0.
In mode 0 the oom killer gets used. I wanted to avoid that.

```
In mode 0, calls of mmap(2) with MAP_NORESERVE are not
       checked, and the default check is very weak, leading to the
       risk of getting a process "OOM-killed".
```
This does not sound very useful. Maybe when my memory is full I should not be able to launch more stuff instead. I am not sure. I do not have programs running I want to get killed.

**Comment by idnovic** [comment]
`vm.overcommit_ratio=75`
So far I found out that I need to set this to at least 100 while I have mode 2 set up. Currently, I am virtually shrinking my available memory. Also `GIGACAGE_ENABLED` seems security related so I am not going to use the work around.

**Comment by idnovic** [comment]
I changed it back to mode 0 (default). vm.overcommit_ratio does not apply in mode 0. Did you find anything useful in the log files I uploaded?

**Comment by X3n0m0rph59** [comment]
> I changed it back to mode 0 (default)

Yes, that's the only reasonable choice for desktop systems.

> Did you find anything useful in the log files I uploaded?

I did not find anything useful, so it is unclear what exactly happened during the load spikes.

**Comment by idnovic** [comment]
I believe you can close this issue now.
I do not have problems with the version 1.7.1
