### ISSUE TITLE
run as non root

### ISSUE THREAD

**Issue by idnovic** [X3n0m0rph59/precached#15]
So what are the possibilities of precached running as non root user?

Because precached just needs read access to /.
Maybe use a `precached` user instead.

This would completely drop the possibility of precached overwriting files.
Precached working directories can just be of the same user/group as precached is.

**Comment by X3n0m0rph59** [comment]
I will add code to actually honor the available configuration parameters. Will need to rework the code that really needs root capabilities to work.

**Comment by idnovic** [comment]
What features need root capabilities?
Maybe it is possible to grant special capabilities to the precached process.
Or launch as root and drop user/capabilities. Dnsmasq does this.

Even thought their may be directories which precached as non root would have no access rights to I think that may work. As example under /boot not everything is accessible by non root users.

**Comment by X3n0m0rph59** [comment]
I nearly have it working right now.

> What features need root capabilities?

* netlink connector
* fanotify
* procfs access
....

Most of them can be acquired at startup, before we drop privileges.
Dynamic procfs access during process lifetime will need `CAP_DAC_READ_SEARCH`.

> Maybe it is possible to grant special capabilities to the precached process.
Or launch as root and drop user/capabilities.

Yes, I implemented both ways.

**Comment by idnovic** [comment]
I am running precached now as non root precached user.
For precachedtop I now need to use sudo. But that is fine.

It seems to work well but between the #14 and the new features I can not say right now.

**Comment by X3n0m0rph59** [comment]
We now have full support for running as non-root user, so I will close this issue.
