### ISSUE TITLE
decrease cpu usage over time

### ISSUE THREAD

**Issue by idnovic** [X3n0m0rph59/precached#16]
By looking at the CPU time metrics of gnome system monitor I found out that precached used 42 hours worth of CPU time. Compared to 45 minutes for journald and 12 hours for gnome. Firefox had 14 hours of CPU time. Ananicy (rule based nice daemon) had 2 hours.

The above findings were measured in the same time frame. Every program was running for 2.5 hours (uptime of the system).

I am thinking about battery based systems. After the initial preload during power up, use a bigger sleep timer. Maybe it is possible to drop the CPU time of precached by 3 or 4.
Maybe use an algorithm to defer or stop the creation of new profiles while the system is running without power cable attached.

**Comment by X3n0m0rph59** [comment]
Thanks for bringing this to my attention.
As a first measure, I will increase the back-off time of the fanotify thread.

**Comment by idnovic** [comment]
I wanted to add since we are investigation the high CPU usage bug in the other issue that the measured numbers here were from a not yet failed/buged precached process. 

Also maybe it is worth to repeat the test since the gnome system monitor may have its own bugs.

If you have suggestions for the right tools to use tell me.

**Comment by idnovic** [comment]
`top -p PID`

Gives the same output as gnome system monitor. I am running the test again. First sample in 2 hours.

**Comment by idnovic** [comment]
![Bildschirmfoto vom 2019-07-11 17-26-28](https://user-images.githubusercontent.com/28260793/61063886-495fbb80-a3f0-11e9-8318-988caabfd371.png)

In the same time gnome and Firefox had around 10 hours worth of CPU time.
This test was with the newest version after a full reset and restart.

I will repeat is one more time later.

**Comment by idnovic** [comment]
![Bildschirmfoto vom 2019-07-11 20-05-39](https://user-images.githubusercontent.com/28260793/61074132-88990700-a406-11e9-94db-57e447f1b27a.png)

Above is the same test again.

For the last test I am running without power cable attached and watching at powertop. Results in 1 hour.

**Comment by idnovic** [comment]
Okay so I did run powertop but without calibration.
I would say precached runs now battery friendly. Powertop displays the utilization in wake ups per second and events as float.

It seems that precached has little background utilization and the only increase is during the preloading phase after a memory hungry process closes.

**Comment by idnovic** [comment]
![Bildschirmfoto vom 2019-07-11 21-25-12](https://user-images.githubusercontent.com/28260793/61079145-c9e2e400-a411-11e9-9d08-78d2c14da745.png)

Only precachedtop while active polling is not battery friendly. Against Firefox, I suppose that precachedtop should use less energy.

**Comment by idnovic** [comment]
I believe you can close this issue now.

Precached has 8 hours against gnome with 48 hours and Firefox with 58 hours.
Uptime of the system 7 hours and 30 minutes.
