### ISSUE TITLE
hot-applications list displays same item multiple times

### ISSUE THREAD

**Issue by idnovic** [X3n0m0rph59/precached#20]
I saw that I have the same item multiple times in the hot-applications list.
Is this expected?

```
Abgeschlossen                                                                   +-----+-----------------------------------------------------------+----------------------+--------+
|   # | Ausführbare Datei                                         | Hash                 | Anzahl |
+-----+-----------------------------------------------------------+----------------------+--------+
|   1 | /usr/bin/ionice                                           | 6745466777889424043  |   1312 |
+-----+-----------------------------------------------------------+----------------------+--------+
|   2 | /usr/bin/ionice                                           | 9253562639802036953  |    815 |
+-----+-----------------------------------------------------------+----------------------+--------+
|   3 | /usr/bin/ionice                                           | 11100230901800630663 |    799 |
+-----+-----------------------------------------------------------+----------------------+--------+
|   4 | /usr/bin/ionice                                           | 12164354706907101889 |    789 |
+-----+-----------------------------------------------------------+-------------
```

[precachedctl_plugins_hot-applications_list.log.zip](https://github.com/X3n0m0rph59/precached/files/3387134/precachedctl_plugins_hot-applications_list.log.zip)

**Comment by X3n0m0rph59** [comment]
Yes, this is expected! These entries differ only in their respective command lines.
You may view the different command lines by using this command:

`$ sudo iotracectl info -e ionice`

Precached not only uses the file name of an executable file, but also uses the full command line with which this binary has been invoked, to perform prefetching. This has certain advantages, like gaining the ability to discriminate things like `libreoffice --calc` and `libreoffice --writer`. Therefore duplicate entries are a feature, not a bug!

**Comment by idnovic** [comment]
Good to know. Can you append the command line part to the precachedtop process list?
I have on process only displayed as python. I know which process it is but the displaying of it is still not clear enough.

Displayed is only python
the full command goes along the lines of python ananicy -p .....
