### ISSUE TITLE
Do files in cache become to old?

### ISSUE THREAD

**Issue by idnovic** [X3n0m0rph59/precached#7]
Imagine a file cached via precached changes on the disk after precached loaded it into mem.
Now this file is accessed. Is the cached version preferred or is the disk version loaded?

I am asking because I updated a gnome shell extension by replacing the files. Then I used gnome-tweak to unload and reload the extension. But the old version of the extension was loaded. I do not know if precached had something to do with it or just a coincidence.

**Comment by X3n0m0rph59** [comment]
> Imagine a file cached via precached changes on the disk after precached loaded it into mem. Now this file is accessed. Is the cached version preferred or is the disk version loaded?

The new content of the file will be given out by the Linux kernel, to processes reading/mapping that file. 

> I am asking because I updated a gnome shell extension by replacing the files. Then I used gnome-tweak to unload and reload the extension. But the old version of the extension was loaded. I do not know if precached had something to do with it or just a coincidence.

I currently don't see how precached could lead to the aforementioned problem.

**Comment by idnovic** [comment]
Well it is possibly gnomes fault. I also cherry picked around 20 patches from master.
Wayland is not yet perfect with gnome. So maybe my setup is the reason and the extension was not really unloaded from the gnome-shell.
